version: 1.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore Source
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: Environment
  name: NuGet Public
  on:
    branch: master
